{
  "name": "temple-meals-api",
  "version": "1.0.0",
  "description": "Temple Meal Management System - Backend API",
  "main": "src/server.js",
  "type": "module",
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon src/server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.18.2",
    "mongoose": "^8.5.0",
    "dotenv": "^16.4.5",
    "cors": "^2.8.5",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0",
    "bcryptjs": "^2.4.3",
    "jsonwebtoken": "^9.1.2"
  },
  "devDependencies": {
    "nodemon": "^3.1.11"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}
